name: my_heart_son
description: "칭찬 나무 프로젝트"
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  file_picker: ^8.0.0+1
  flutter_secure_storage: ^9.2.2
  flutter_screenutil: ^5.9.3
  image_picker: ^1.0.8
  image: ^4.5.0
  custom_image_crop: ^0.0.13
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: CookieRun
      fonts:
        - asset: assets/fonts/CookieRun-Regular.ttf
